-- Prepared locally; apply before enabling AXEL/qUINT jobs.
BEGIN;

CREATE TABLE public.axel_products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_parent_id text NOT NULL,
  source_color_id text NOT NULL,
  source_url text NOT NULL,
  canonical_url text NOT NULL,
  source_product_number text,
  name text NOT NULL,
  brand text,
  product_type text,
  color text,
  color_group text,
  current_price numeric CHECK (current_price >= 0),
  list_price numeric CHECK (list_price > current_price),
  currency text NOT NULL DEFAULT 'DKK' CHECK (currency = 'DKK'),
  description text,
  materials text[] NOT NULL DEFAULT '{}',
  fit text,
  category text,
  category_path text[] NOT NULL DEFAULT '{}',
  specifications jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(specifications) = 'object'),
  images text[] NOT NULL DEFAULT '{}',
  size_guide jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(size_guide) = 'object'),
  webshop_sizes jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(webshop_sizes) = 'array'),
  local_inventory jsonb NOT NULL DEFAULT '{"stores":{}}'
    CHECK (jsonb_typeof(local_inventory) = 'object' AND local_inventory ? 'stores' AND jsonb_typeof(local_inventory->'stores') = 'object'),
  local_total_stock integer CHECK (local_total_stock >= 0),
  local_available boolean,
  aarhus_total_stock integer CHECK (aarhus_total_stock >= 0),
  aarhus_available boolean,
  inventory_checked_at timestamptz,
  publication_status text NOT NULL DEFAULT 'active' CHECK (publication_status IN ('active','unavailable','missing')),
  status_reason text,
  status_checked_at timestamptz,
  discontinued_at timestamptz,
  last_seen_in_catalog_at timestamptz,
  consecutive_catalog_misses integer NOT NULL DEFAULT 0 CHECK (consecutive_catalog_misses >= 0),
  raw jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(raw) = 'object'),
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  scraped_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_parent_id, source_color_id)
);
CREATE INDEX axel_products_active_updated_idx ON public.axel_products (updated_at, id) WHERE publication_status = 'active';
CREATE INDEX axel_products_recent_idx ON public.axel_products (first_seen_at DESC) WHERE publication_status = 'active';
CREATE INDEX axel_products_aarhus_idx ON public.axel_products (id) WHERE aarhus_available;
ALTER TABLE public.axel_products ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.axel_products FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.axel_products TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.axel_products_id_seq TO service_role;
COMMENT ON TABLE public.axel_products IS 'One axel style-colour row; exact public Aarhus shop inventory only, separate from online stock.';
COMMENT ON COLUMN public.axel_products.source_parent_id IS 'Stable public Relewise parentId; colour key is Alpine options colorId.';
COMMENT ON COLUMN public.axel_products.size_guide IS 'Published size-guide tables; source guidance is not a per-product measurement guarantee.';

CREATE TABLE public.quint_products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_parent_id text NOT NULL,
  source_color_id text NOT NULL,
  source_url text NOT NULL,
  canonical_url text NOT NULL,
  source_product_number text,
  name text NOT NULL,
  brand text,
  product_type text,
  color text,
  color_group text,
  current_price numeric CHECK (current_price >= 0),
  list_price numeric CHECK (list_price > current_price),
  currency text NOT NULL DEFAULT 'DKK' CHECK (currency = 'DKK'),
  description text,
  materials text[] NOT NULL DEFAULT '{}',
  fit text,
  category text,
  category_path text[] NOT NULL DEFAULT '{}',
  specifications jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(specifications) = 'object'),
  images text[] NOT NULL DEFAULT '{}',
  size_guide jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(size_guide) = 'object'),
  webshop_sizes jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(webshop_sizes) = 'array'),
  local_inventory jsonb NOT NULL DEFAULT '{"stores":{}}'
    CHECK (jsonb_typeof(local_inventory) = 'object' AND local_inventory ? 'stores' AND jsonb_typeof(local_inventory->'stores') = 'object'),
  local_total_stock integer CHECK (local_total_stock >= 0),
  local_available boolean,
  aarhus_total_stock integer CHECK (aarhus_total_stock >= 0),
  aarhus_available boolean,
  inventory_checked_at timestamptz,
  publication_status text NOT NULL DEFAULT 'active' CHECK (publication_status IN ('active','unavailable','missing')),
  status_reason text,
  status_checked_at timestamptz,
  discontinued_at timestamptz,
  last_seen_in_catalog_at timestamptz,
  consecutive_catalog_misses integer NOT NULL DEFAULT 0 CHECK (consecutive_catalog_misses >= 0),
  raw jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(raw) = 'object'),
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  scraped_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_parent_id, source_color_id)
);
CREATE INDEX quint_products_active_updated_idx ON public.quint_products (updated_at, id) WHERE publication_status = 'active';
CREATE INDEX quint_products_recent_idx ON public.quint_products (first_seen_at DESC) WHERE publication_status = 'active';
CREATE INDEX quint_products_aarhus_idx ON public.quint_products (id) WHERE aarhus_available;
ALTER TABLE public.quint_products ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.quint_products FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.quint_products TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.quint_products_id_seq TO service_role;
COMMENT ON TABLE public.quint_products IS 'One quint style-colour row; exact public Aarhus shop inventory only, separate from online stock.';
COMMENT ON COLUMN public.quint_products.source_parent_id IS 'Stable public Relewise parentId; colour key is Alpine options colorId.';
COMMENT ON COLUMN public.quint_products.size_guide IS 'Published size-guide tables; source guidance is not a per-product measurement guarantee.';

ALTER TABLE public.store_inventory_history DROP CONSTRAINT store_inventory_history_store_check;
ALTER TABLE public.store_inventory_history ADD CONSTRAINT store_inventory_history_store_check CHECK
  (store IN ('rains','romerhus','suitclub','cejf','skagen_clothing','shoechapter','stoy','lakor','axel','quint'));
ALTER TABLE public.catalog_sync_runs DROP CONSTRAINT catalog_sync_runs_store_check;
ALTER TABLE public.catalog_sync_runs ADD CONSTRAINT catalog_sync_runs_store_check CHECK
  (store IN ('kaufmann','rains','romerhus','suitclub','cejf','skagen_clothing','shoechapter','stoy','lakor','axel','quint'));
-- store_inventory_refresh_runs only requires a nonempty selected_stores array;
-- it has no store-name allowlist to extend.
COMMIT;
