create table if not exists public.store_inventory_history (
  id bigint generated by default as identity primary key,
  store text not null,
  product_id bigint not null,
  state_hash text not null,
  observed_from timestamptz not null,
  observed_through timestamptz not null,
  last_observed_bucket date not null,
  observation_count integer not null default 1,
  refresh_status text not null default 'ok',
  current_price numeric,
  list_price numeric,
  local_inventory jsonb not null default '{"stores": {}}'::jsonb,
  local_total_stock integer,
  local_available boolean,
  aarhus_total_stock integer,
  aarhus_available boolean,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint store_inventory_history_store_check
    check (
      store in (
        'rains',
        'romerhus',
        'suitclub',
        'cejf',
        'skagen_clothing',
        'shoechapter',
        'stoy',
        'lakor'
      )
    ),
  constraint store_inventory_history_observation_count_check
    check (observation_count > 0),
  constraint store_inventory_history_observed_range_check
    check (observed_through >= observed_from)
);

create index if not exists store_inventory_history_product_observed_idx
  on public.store_inventory_history
    (store, product_id, observed_through desc, id desc);

create index if not exists store_inventory_history_store_bucket_idx
  on public.store_inventory_history (store, last_observed_bucket desc);

alter table public.store_inventory_history enable row level security;

comment on table public.store_inventory_history is
  'Change-based price and local-store inventory history for non-Kaufmann products. Consecutive identical observations extend one interval.';

comment on column public.store_inventory_history.product_id is
  'Database product-row id scoped by store; products live in separate store tables, so there is no single foreign-key target.';

comment on column public.store_inventory_history.observation_count is
  'Number of distinct UTC days on which this exact state was observed during the interval.';

comment on column public.store_inventory_history.state_hash is
  'Database-generated fingerprint of stored dynamic fields. Webshop sizes are intentionally excluded from history.';

create or replace function public.merge_store_inventory_history_observation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  previous_row public.store_inventory_history%rowtype;
begin
  new.local_inventory := coalesce(
    new.local_inventory,
    '{"stores": {}}'::jsonb
  );
  new.state_hash := md5(
    jsonb_build_object(
      'refresh_status', new.refresh_status,
      'current_price', new.current_price,
      'list_price', new.list_price,
      'local_inventory', new.local_inventory,
      'local_total_stock', new.local_total_stock,
      'local_available', new.local_available,
      'aarhus_total_stock', new.aarhus_total_stock,
      'aarhus_available', new.aarhus_available
    )::text
  );

  select history.*
  into previous_row
  from public.store_inventory_history as history
  where history.store = new.store
    and history.product_id = new.product_id
  order by history.observed_through desc, history.id desc
  limit 1
  for update;

  if found and previous_row.state_hash = new.state_hash then
    update public.store_inventory_history
    set
      observed_through = greatest(previous_row.observed_through, new.observed_through),
      last_observed_bucket = greatest(
        previous_row.last_observed_bucket,
        new.last_observed_bucket
      ),
      observation_count = previous_row.observation_count + case
        when new.last_observed_bucket > previous_row.last_observed_bucket then 1
        else 0
      end,
      updated_at = greatest(previous_row.updated_at, new.updated_at)
    where id = previous_row.id;

    return null;
  end if;

  return new;
end
$$;

revoke all on function public.merge_store_inventory_history_observation()
  from public, anon, authenticated;
grant execute on function public.merge_store_inventory_history_observation()
  to service_role;

drop trigger if exists store_inventory_history_merge_observation
  on public.store_inventory_history;

create trigger store_inventory_history_merge_observation
before insert on public.store_inventory_history
for each row
execute function public.merge_store_inventory_history_observation();

-- Preserve existing daily history as compact intervals. Source identities and
-- webshop sizes remain available on live product rows and are not duplicated.
with source_states as (
  select
    snapshots.*,
    md5(
      jsonb_build_object(
        'refresh_status', snapshots.refresh_status,
        'current_price', snapshots.current_price,
        'list_price', snapshots.list_price,
        'local_inventory', snapshots.local_inventory,
        'local_total_stock', snapshots.local_total_stock,
        'local_available', snapshots.local_available,
        'aarhus_total_stock', snapshots.aarhus_total_stock,
        'aarhus_available', snapshots.aarhus_available
      )::text
    ) as calculated_state_hash
  from public.store_inventory_snapshots as snapshots
  where not exists (
    select 1
    from public.store_inventory_history
  )
), marked_states as (
  select
    source_states.*,
    case
      when lag(calculated_state_hash) over (
        partition by store, product_id
        order by checked_at, id
      ) is distinct from calculated_state_hash then 1
      else 0
    end as starts_new_interval
  from source_states
), numbered_states as (
  select
    marked_states.*,
    sum(starts_new_interval) over (
      partition by store, product_id
      order by checked_at, id
      rows between unbounded preceding and current row
    ) as interval_number
  from marked_states
), compact_intervals as (
  select
    store,
    product_id,
    interval_number,
    min(checked_at) as observed_from,
    max(checked_at) as observed_through,
    max(checked_bucket) as last_observed_bucket,
    count(distinct checked_bucket)::integer as observation_count,
    (array_agg(refresh_status order by checked_at, id))[1] as refresh_status,
    (array_agg(current_price order by checked_at, id))[1] as current_price,
    (array_agg(list_price order by checked_at, id))[1] as list_price,
    (array_agg(local_inventory order by checked_at, id))[1] as local_inventory,
    (array_agg(local_total_stock order by checked_at, id))[1] as local_total_stock,
    (array_agg(local_available order by checked_at, id))[1] as local_available,
    (array_agg(aarhus_total_stock order by checked_at, id))[1] as aarhus_total_stock,
    (array_agg(aarhus_available order by checked_at, id))[1] as aarhus_available,
    min(created_at) as created_at,
    max(updated_at) as updated_at
  from numbered_states
  group by store, product_id, interval_number
)
insert into public.store_inventory_history (
  store,
  product_id,
  state_hash,
  observed_from,
  observed_through,
  last_observed_bucket,
  observation_count,
  refresh_status,
  current_price,
  list_price,
  local_inventory,
  local_total_stock,
  local_available,
  aarhus_total_stock,
  aarhus_available,
  created_at,
  updated_at
)
select
  store,
  product_id,
  '' as state_hash,
  observed_from,
  observed_through,
  last_observed_bucket,
  observation_count,
  refresh_status,
  current_price,
  list_price,
  local_inventory,
  local_total_stock,
  local_available,
  aarhus_total_stock,
  aarhus_available,
  created_at,
  updated_at
from compact_intervals
order by store, product_id, observed_from;

-- Keep the compact table complete while a droplet may still be running the
-- previous release. Remove this bridge when the legacy table is retired.
create or replace function public.mirror_legacy_store_inventory_snapshot()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  insert into public.store_inventory_history (
    store,
    product_id,
    state_hash,
    observed_from,
    observed_through,
    last_observed_bucket,
    observation_count,
    refresh_status,
    current_price,
    list_price,
    local_inventory,
    local_total_stock,
    local_available,
    aarhus_total_stock,
    aarhus_available,
    created_at,
    updated_at
  )
  values (
    new.store,
    new.product_id,
    'pending',
    new.checked_at,
    new.checked_at,
    new.checked_bucket,
    1,
    new.refresh_status,
    new.current_price,
    new.list_price,
    new.local_inventory,
    new.local_total_stock,
    new.local_available,
    new.aarhus_total_stock,
    new.aarhus_available,
    new.created_at,
    new.updated_at
  );

  return new;
end
$$;

revoke all on function public.mirror_legacy_store_inventory_snapshot()
  from public, anon, authenticated;
grant execute on function public.mirror_legacy_store_inventory_snapshot()
  to service_role;

drop trigger if exists store_inventory_snapshots_mirror_history
  on public.store_inventory_snapshots;

create trigger store_inventory_snapshots_mirror_history
after insert or update on public.store_inventory_snapshots
for each row
execute function public.mirror_legacy_store_inventory_snapshot();

create table if not exists public.store_inventory_refresh_runs (
  id uuid primary key,
  mode text not null,
  selected_stores text[] not null,
  status text not null default 'running',
  started_at timestamptz not null,
  finished_at timestamptz,
  row_limit integer,
  row_offset integer not null default 0,
  history_enabled boolean not null default true,
  stores_planned integer not null default 0,
  stores_completed integer not null default 0,
  failed_stores integer not null default 0,
  pages_processed integer not null default 0,
  updated_products integer not null default 0,
  unavailable_products integer not null default 0,
  history_observations integer not null default 0,
  failed_products integer not null default 0,
  skipped_products integer not null default 0,
  write_failed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint store_inventory_refresh_runs_mode_check
    check (mode in ('all', 'selected')),
  constraint store_inventory_refresh_runs_status_check
    check (status in ('running', 'succeeded', 'partial', 'failed')),
  constraint store_inventory_refresh_runs_selected_stores_check
    check (cardinality(selected_stores) > 0),
  constraint store_inventory_refresh_runs_limit_check
    check (row_limit is null or row_limit > 0),
  constraint store_inventory_refresh_runs_offset_check
    check (row_offset >= 0),
  constraint store_inventory_refresh_runs_counts_check
    check (
      stores_planned >= 0
      and stores_completed >= 0
      and failed_stores >= 0
      and pages_processed >= 0
      and updated_products >= 0
      and unavailable_products >= 0
      and history_observations >= 0
      and failed_products >= 0
      and skipped_products >= 0
    )
);

create index if not exists store_inventory_refresh_runs_started_at_idx
  on public.store_inventory_refresh_runs (started_at desc);

alter table public.store_inventory_refresh_runs enable row level security;

comment on table public.store_inventory_refresh_runs is
  'One small operational record per sequential non-Kaufmann inventory refresh invocation.';
