-- Salling/Magasin Aarhus ingestion. Apply before deploying the new --all jobs.
BEGIN;

CREATE TABLE public.salling_products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_parent_id text NOT NULL,
  source_color_id text NOT NULL,
  source_url text NOT NULL,
  canonical_url text NOT NULL,
  name text NOT NULL,
  brand text,
  product_type text,
  color text,
  color_group text,
  current_price numeric CHECK (current_price >= 0),
  list_price numeric CHECK (list_price > current_price),
  currency text NOT NULL DEFAULT 'DKK' CHECK (currency = 'DKK'),
  description text,
  materials text[] NOT NULL DEFAULT '{}',
  fit text,
  category text,
  category_path text[] NOT NULL DEFAULT '{}',
  specifications jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(specifications) = 'object'),
  images text[] NOT NULL DEFAULT '{}',
  webshop_sizes jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(webshop_sizes) = 'array'),
  local_inventory jsonb NOT NULL DEFAULT '{"stores":{}}'
    CHECK (jsonb_typeof(local_inventory) = 'object' AND local_inventory ? 'stores' AND jsonb_typeof(local_inventory->'stores') = 'object'),
  local_total_stock integer CHECK (local_total_stock >= 0),
  local_available boolean,
  aarhus_total_stock integer CHECK (aarhus_total_stock >= 0),
  aarhus_available boolean,
  inventory_checked_at timestamptz,
  publication_status text NOT NULL DEFAULT 'active' CHECK (publication_status IN ('active','unavailable','missing')),
  status_reason text,
  status_checked_at timestamptz,
  discontinued_at timestamptz,
  last_seen_in_catalog_at timestamptz,
  consecutive_catalog_misses integer NOT NULL DEFAULT 0 CHECK (consecutive_catalog_misses >= 0),
  raw jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(raw) = 'object'),
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  scraped_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_parent_id, source_color_id)
);
CREATE INDEX salling_products_active_updated_idx ON public.salling_products (updated_at, id) WHERE publication_status = 'active';
CREATE INDEX salling_products_recent_idx ON public.salling_products (first_seen_at DESC) WHERE publication_status = 'active';
CREATE INDEX salling_products_aarhus_idx ON public.salling_products (id) WHERE aarhus_available;
ALTER TABLE public.salling_products ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.salling_products FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.salling_products TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.salling_products_id_seq TO service_role;


CREATE TABLE public.magasin_products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_parent_id text NOT NULL,
  source_color_id text NOT NULL,
  source_url text NOT NULL,
  canonical_url text NOT NULL,
  source_product_number text,
  name text NOT NULL,
  brand text,
  product_type text,
  color text,
  color_group text,
  current_price numeric CHECK (current_price >= 0),
  list_price numeric CHECK (list_price > current_price),
  currency text NOT NULL DEFAULT 'DKK' CHECK (currency = 'DKK'),
  description text,
  materials text[] NOT NULL DEFAULT '{}',
  fit text,
  category text,
  category_path text[] NOT NULL DEFAULT '{}',
  specifications jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(specifications) = 'object'),
  images text[] NOT NULL DEFAULT '{}',
  size_guide jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(size_guide) = 'object'),
  care_instructions jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(care_instructions) = 'array'),
  webshop_sizes jsonb NOT NULL DEFAULT '[]' CHECK (jsonb_typeof(webshop_sizes) = 'array'),
  local_inventory jsonb NOT NULL DEFAULT '{"stores":{}}'
    CHECK (jsonb_typeof(local_inventory) = 'object' AND local_inventory ? 'stores' AND jsonb_typeof(local_inventory->'stores') = 'object'),
  local_total_stock integer CHECK (local_total_stock >= 0),
  local_available boolean,
  aarhus_total_stock integer CHECK (aarhus_total_stock >= 0),
  aarhus_available boolean,
  inventory_checked_at timestamptz,
  publication_status text NOT NULL DEFAULT 'active' CHECK (publication_status IN ('active','unavailable','missing')),
  status_reason text,
  status_checked_at timestamptz,
  discontinued_at timestamptz,
  last_seen_in_catalog_at timestamptz,
  consecutive_catalog_misses integer NOT NULL DEFAULT 0 CHECK (consecutive_catalog_misses >= 0),
  raw jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(raw) = 'object'),
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  scraped_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_parent_id, source_color_id)
);
CREATE INDEX magasin_products_active_updated_idx ON public.magasin_products (updated_at, id) WHERE publication_status = 'active';
CREATE INDEX magasin_products_recent_idx ON public.magasin_products (first_seen_at DESC) WHERE publication_status = 'active';
CREATE INDEX magasin_products_aarhus_idx ON public.magasin_products (id) WHERE aarhus_available;
ALTER TABLE public.magasin_products ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.magasin_products FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.magasin_products TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.magasin_products_id_seq TO service_role;


COMMENT ON COLUMN public.salling_products.source_parent_id IS 'Salling parentId; source_color_id is NFKC/casefolded Variantfarve, independent of size and stock.';
COMMENT ON COLUMN public.salling_products.local_inventory IS 'Aarhus size quantities from indexableStockInfo. Explicitly disabled size pages returning 404 remain unknown, not zero.';
COMMENT ON COLUMN public.magasin_products.source_parent_id IS 'Magasin masterProductID; source_color_id is colorVariantId, independent of size and stock.';
COMMENT ON COLUMN public.magasin_products.local_inventory IS 'Aarhus boolean availability per size. No quantities are published; all stock fields remain null.';
ALTER TABLE public.store_inventory_history DROP CONSTRAINT store_inventory_history_store_check;
ALTER TABLE public.store_inventory_history ADD CONSTRAINT store_inventory_history_store_check CHECK
  (store IN ('rains','romerhus','suitclub','cejf','skagen_clothing','shoechapter','stoy','lakor','axel','quint','salling','magasin'));
ALTER TABLE public.catalog_sync_runs DROP CONSTRAINT catalog_sync_runs_store_check;
ALTER TABLE public.catalog_sync_runs ADD CONSTRAINT catalog_sync_runs_store_check CHECK
  (store IN ('kaufmann','rains','romerhus','suitclub','cejf','skagen_clothing','shoechapter','stoy','lakor','axel','quint','salling','magasin'));
COMMIT;
