create table if not exists public.kaufmann_inventory_history (
  id bigint generated by default as identity primary key,
  kaufmann_product_id bigint not null
    references public.kaufmann_products(id) on delete cascade,
  state_hash text not null,
  observed_from timestamptz not null,
  observed_through timestamptz not null,
  last_observed_bucket date not null,
  observation_count integer not null default 1,
  refresh_status text not null default 'ok',
  current_price numeric,
  list_price numeric,
  aarhus_inventory jsonb not null default '{"stores": {}}'::jsonb,
  aarhus_total_stock integer not null default 0,
  aarhus_available boolean not null default false,
  source_available boolean,
  publication_status text,
  status_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint kaufmann_inventory_history_observation_count_check
    check (observation_count > 0),
  constraint kaufmann_inventory_history_observed_range_check
    check (observed_through >= observed_from),
  constraint kaufmann_inventory_history_publication_status_check
    check (
      publication_status is null
      or publication_status in ('active', 'unavailable', 'missing')
    )
);

create index if not exists kaufmann_inventory_history_product_observed_idx
  on public.kaufmann_inventory_history
    (kaufmann_product_id, observed_through desc, id desc);

create index if not exists kaufmann_inventory_history_last_bucket_idx
  on public.kaufmann_inventory_history (last_observed_bucket desc);

alter table public.kaufmann_inventory_history enable row level security;

comment on table public.kaufmann_inventory_history is
  'Change-based Kaufmann price and Aarhus inventory history. Consecutive identical observations extend one interval instead of copying JSON every day.';

comment on column public.kaufmann_inventory_history.observation_count is
  'Number of distinct UTC days on which this exact state was observed during the interval.';

comment on column public.kaufmann_inventory_history.state_hash is
  'Database-generated fingerprint of the stored dynamic fields. Webshop sizes are intentionally excluded from history.';

create or replace function public.merge_kaufmann_inventory_history_observation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  previous_row public.kaufmann_inventory_history%rowtype;
begin
  new.state_hash := md5(
    jsonb_build_object(
      'refresh_status', new.refresh_status,
      'current_price', new.current_price,
      'list_price', new.list_price,
      'aarhus_inventory', new.aarhus_inventory,
      'aarhus_total_stock', new.aarhus_total_stock,
      'aarhus_available', new.aarhus_available,
      'source_available', new.source_available,
      'publication_status', new.publication_status,
      'status_reason', new.status_reason
    )::text
  );

  select history.*
  into previous_row
  from public.kaufmann_inventory_history as history
  where history.kaufmann_product_id = new.kaufmann_product_id
  order by history.observed_through desc, history.id desc
  limit 1
  for update;

  if found and previous_row.state_hash = new.state_hash then
    update public.kaufmann_inventory_history
    set
      observed_through = greatest(previous_row.observed_through, new.observed_through),
      last_observed_bucket = greatest(
        previous_row.last_observed_bucket,
        new.last_observed_bucket
      ),
      observation_count = previous_row.observation_count + case
        when new.last_observed_bucket > previous_row.last_observed_bucket then 1
        else 0
      end,
      updated_at = greatest(previous_row.updated_at, new.updated_at)
    where id = previous_row.id;

    return null;
  end if;

  return new;
end
$$;

revoke all on function public.merge_kaufmann_inventory_history_observation()
  from public, anon, authenticated;
grant execute on function public.merge_kaufmann_inventory_history_observation()
  to service_role;

drop trigger if exists kaufmann_inventory_history_merge_observation
  on public.kaufmann_inventory_history;

create trigger kaufmann_inventory_history_merge_observation
before insert on public.kaufmann_inventory_history
for each row
execute function public.merge_kaufmann_inventory_history_observation();

-- Preserve the existing history in compact form. Webshop-only inventory and
-- repeated source identity are deliberately not copied into the new table.
with source_states as (
  select
    snapshots.*,
    md5(
      jsonb_build_object(
        'refresh_status', snapshots.refresh_status,
        'current_price', snapshots.current_price,
        'list_price', snapshots.list_price,
        'aarhus_inventory', snapshots.aarhus_inventory,
        'aarhus_total_stock', snapshots.aarhus_total_stock,
        'aarhus_available', snapshots.aarhus_available,
        'source_available', snapshots.source_available,
        'publication_status', snapshots.publication_status,
        'status_reason', snapshots.status_reason
      )::text
    ) as calculated_state_hash
  from public.kaufmann_inventory_snapshots as snapshots
  where not exists (
    select 1
    from public.kaufmann_inventory_history
  )
), marked_states as (
  select
    source_states.*,
    case
      when lag(calculated_state_hash) over (
        partition by kaufmann_product_id
        order by checked_at, id
      ) is distinct from calculated_state_hash then 1
      else 0
    end as starts_new_interval
  from source_states
), numbered_states as (
  select
    marked_states.*,
    sum(starts_new_interval) over (
      partition by kaufmann_product_id
      order by checked_at, id
      rows between unbounded preceding and current row
    ) as interval_number
  from marked_states
), compact_intervals as (
  select
    kaufmann_product_id,
    interval_number,
    min(checked_at) as observed_from,
    max(checked_at) as observed_through,
    max(checked_bucket) as last_observed_bucket,
    count(distinct checked_bucket)::integer as observation_count,
    (array_agg(refresh_status order by checked_at, id))[1] as refresh_status,
    (array_agg(current_price order by checked_at, id))[1] as current_price,
    (array_agg(list_price order by checked_at, id))[1] as list_price,
    (array_agg(aarhus_inventory order by checked_at, id))[1] as aarhus_inventory,
    (array_agg(aarhus_total_stock order by checked_at, id))[1] as aarhus_total_stock,
    (array_agg(aarhus_available order by checked_at, id))[1] as aarhus_available,
    (array_agg(source_available order by checked_at, id))[1] as source_available,
    (array_agg(publication_status order by checked_at, id))[1] as publication_status,
    (array_agg(status_reason order by checked_at, id))[1] as status_reason,
    min(created_at) as created_at,
    max(updated_at) as updated_at
  from numbered_states
  group by kaufmann_product_id, interval_number
)
insert into public.kaufmann_inventory_history (
  kaufmann_product_id,
  state_hash,
  observed_from,
  observed_through,
  last_observed_bucket,
  observation_count,
  refresh_status,
  current_price,
  list_price,
  aarhus_inventory,
  aarhus_total_stock,
  aarhus_available,
  source_available,
  publication_status,
  status_reason,
  created_at,
  updated_at
)
select
  kaufmann_product_id,
  '' as state_hash,
  observed_from,
  observed_through,
  last_observed_bucket,
  observation_count,
  refresh_status,
  current_price,
  list_price,
  aarhus_inventory,
  aarhus_total_stock,
  aarhus_available,
  source_available,
  publication_status,
  status_reason,
  created_at,
  updated_at
from compact_intervals
order by kaufmann_product_id, observed_from;

create table if not exists public.kaufmann_inventory_refresh_runs (
  id uuid primary key,
  mode text not null,
  status text not null default 'running',
  include_unavailable boolean not null default false,
  started_at timestamptz not null,
  finished_at timestamptz,
  pages_planned integer not null default 0,
  pages_processed integer not null default 0,
  refreshed_variants integer not null default 0,
  unavailable_variants integer not null default 0,
  missing_variants integer not null default 0,
  skipped_new_variants integer not null default 0,
  failed_pages integer not null default 0,
  stopped_early boolean not null default false,
  write_failed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint kaufmann_inventory_refresh_runs_mode_check
    check (mode in ('active', 'all', 'urls')),
  constraint kaufmann_inventory_refresh_runs_status_check
    check (status in ('running', 'succeeded', 'partial', 'failed')),
  constraint kaufmann_inventory_refresh_runs_counts_check
    check (
      pages_planned >= 0
      and pages_processed >= 0
      and refreshed_variants >= 0
      and unavailable_variants >= 0
      and missing_variants >= 0
      and skipped_new_variants >= 0
      and failed_pages >= 0
    )
);

create index if not exists kaufmann_inventory_refresh_runs_started_at_idx
  on public.kaufmann_inventory_refresh_runs (started_at desc);

alter table public.kaufmann_inventory_refresh_runs enable row level security;

comment on table public.kaufmann_inventory_refresh_runs is
  'One small operational record per Kaufmann refresh invocation, including unsuccessful and partial runs.';
